# Generated by Django 5.2.15 on 2026-06-07 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_apps', '0001_initial'),
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('SEND_INVOICE', 'Enviar Comprobante'), ('CHECK_TICKET', 'Consultar Ticket'), ('DOWNLOAD_CDR', 'Descargar CDR'), ('CONSULT_RUC', 'Consultar RUC'), ('CONSULT_DNI', 'Consultar DNI'), ('VOID_DOCUMENT', 'Anular Documento')], db_index=True, help_text='Tipo de operación realizada', max_length=30)),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='Payload enviado a SUNAT', null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict, help_text='Respuesta recibida de SUNAT', null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido'), ('PENDING', 'Pendiente')], db_index=True, default='PENDING', help_text='Estado de la solicitud', max_length=20)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duración de la llamada en milisegundos', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Mensaje de error (si falló)')),
                ('client_app', models.ForeignKey(help_text='Aplicación que originó la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='client_apps.clientapp')),
                ('company', models.ForeignKey(help_text='Empresa que realizó la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='companies.company')),
                ('electronic_document', models.ForeignKey(blank=True, help_text='Documento asociado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='documents.electronicdocument')),
            ],
            options={
                'verbose_name': 'Log de Solicitud',
                'verbose_name_plural': 'Logs de Solicitudes',
                'db_table': 'request_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
