# Generated by Django 6.0.5 on 2026-06-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_log', '0002_alter_requestlog_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='operation',
            field=models.CharField(choices=[('SEND_INVOICE', 'Enviar Comprobante'), ('CHECK_TICKET', 'Consultar Ticket'), ('DOWNLOAD_CDR', 'Descargar CDR'), ('CONSULT_RUC', 'Consultar RUC'), ('CONSULT_DNI', 'Consultar DNI'), ('VOID_DOCUMENT', 'Anular Documento'), ('GET_STATUS', 'Obtener Estado'), ('IDEMPOTENCY_HIT', 'Hit de Idempotencia')], db_index=True, help_text='Tipo de operación realizada', max_length=30),
        ),
    ]
