# Generated by Django 5.2.15 on 2026-06-07 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito')], db_index=True, help_text='Tipo de comprobante (código SUNAT)', max_length=2)),
                ('series', models.CharField(help_text='Serie del comprobante (ej: F001, B001)', max_length=4)),
                ('number', models.PositiveIntegerField(help_text='Número correlativo del comprobante')),
                ('customer_document_type', models.CharField(blank=True, default='', help_text='Tipo de documento del cliente (6=RUC, 1=DNI, etc.)', max_length=2)),
                ('customer_document', models.CharField(help_text='Número de documento del cliente', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', help_text='Nombre o razón social del cliente', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total del comprobante', max_digits=12)),
                ('currency', models.CharField(default='PEN', help_text='Moneda (ISO 4217)', max_length=3)),
                ('xml_path', models.CharField(blank=True, default='', help_text='Ruta del archivo XML firmado', max_length=500)),
                ('zip_path', models.CharField(blank=True, default='', help_text='Ruta del archivo ZIP enviado a SUNAT', max_length=500)),
                ('cdr_zip_path', models.CharField(blank=True, default='', help_text='Ruta del CDR (Constancia de Recepción)', max_length=500)),
                ('hash', models.CharField(blank=True, default='', help_text='Hash del documento firmado', max_length=100)),
                ('sunat_ticket', models.CharField(blank=True, default='', help_text='Ticket de recepción de SUNAT', max_length=100)),
                ('sunat_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('ERROR', 'Error')], db_index=True, default='PENDING', help_text='Estado del comprobante en SUNAT', max_length=20)),
                ('sunat_response_code', models.CharField(blank=True, default='', help_text='Código de respuesta de SUNAT', max_length=10)),
                ('sunat_response', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de SUNAT en JSON', null=True)),
                ('company', models.ForeignKey(help_text='Empresa emisora', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
            ],
            options={
                'verbose_name': 'Documento Electrónico',
                'verbose_name_plural': 'Documentos Electrónicos',
                'db_table': 'electronic_documents',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'series', 'number'), name='unique_document_per_company')],
            },
        ),
    ]
