# Generated by Django 5.2.15 on 2026-06-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_electronicdocument_sunat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicdocument',
            name='sunat_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('GENERATED', 'Generado'), ('SIGNED', 'Firmado'), ('SENT', 'Enviado'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('ERROR', 'Error')], db_index=True, default='PENDING', help_text='Estado del comprobante en SUNAT', max_length=20),
        ),
    ]
