# Generated by Django 5.2.15 on 2026-06-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_electronicdocument_sunat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicdocument',
            name='details',
            field=models.JSONField(default=list, help_text='Lista de ítems de la factura/boleta'),
        ),
    ]
