# Generated by Django 6.0.5 on 2026-06-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_electronicdocument_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicdocument',
            name='sunat_description',
            field=models.TextField(blank=True, default='', help_text='Descripción de respuesta de SUNAT'),
        ),
    ]
