# Generated by Django 6.0.5 on 2026-06-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0005_electronicdocument_sunat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicdocument',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Clave de idempotencia única por empresa', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='electronicdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='unique_idempotency_key_per_company'),
        ),
    ]
