# Generated by Django 5.2.15 on 2026-06-07 02:27

import apps.client_apps.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo de la aplicación (ej: ERP, POS)', max_length=100)),
                ('api_key', models.CharField(db_index=True, default=apps.client_apps.models.generate_api_key, help_text='Clave pública de la API', max_length=100, unique=True)),
                ('api_secret', models.CharField(default=apps.client_apps.models.generate_api_secret, help_text='Clave secreta de la API (mostrar solo al crear)', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si la aplicación puede hacer requests')),
                ('company', models.ForeignKey(help_text='Empresa propietaria de esta aplicación', on_delete=django.db.models.deletion.CASCADE, related_name='client_apps', to='companies.company')),
            ],
            options={
                'verbose_name': 'Aplicación Cliente',
                'verbose_name_plural': 'Aplicaciones Cliente',
                'db_table': 'client_apps',
                'ordering': ['-created_at'],
            },
        ),
    ]
