# Generated by Django 5.2.15 on 2026-06-07 02:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruc', models.CharField(db_index=True, help_text='RUC de la empresa (11 dígitos)', max_length=11, unique=True)),
                ('business_name', models.CharField(help_text='Razón social de la empresa', max_length=255)),
                ('trade_name', models.CharField(blank=True, default='', help_text='Nombre comercial (opcional)', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si la empresa está activa en la plataforma')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
