# Generated by Django 5.2.15 on 2026-06-07 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunatCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sunat_user', models.CharField(help_text='Usuario SOL de SUNAT', max_length=100)),
                ('sunat_password_encrypted', models.TextField(help_text='Contraseña SOL cifrada')),
                ('client_id', models.CharField(blank=True, default='', help_text='Client ID para API REST SUNAT (opcional)', max_length=255)),
                ('client_secret_encrypted', models.TextField(blank=True, default='', help_text='Client Secret cifrado para API REST SUNAT (opcional)')),
                ('certificate', models.TextField(blank=True, default='', help_text='Certificado digital en base64 (opcional)')),
                ('environment', models.CharField(choices=[('BETA', 'Beta (pruebas)'), ('PRODUCTION', 'Producción')], default='BETA', help_text='Entorno de SUNAT (BETA o PRODUCTION)', max_length=20)),
                ('company', models.OneToOneField(help_text='Empresa asociada a estas credenciales', on_delete=django.db.models.deletion.CASCADE, related_name='sunat_credential', to='companies.company')),
            ],
            options={
                'verbose_name': 'Credencial SUNAT',
                'verbose_name_plural': 'Credenciales SUNAT',
                'db_table': 'sunat_credentials',
            },
        ),
    ]
