# Generated by Django 5.2.15 on 2026-06-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunatcredential',
            name='certificate_password_encrypted',
            field=models.TextField(blank=True, default='', help_text='Contraseña del certificado digital cifrada (opcional)'),
        ),
    ]
